#!/usr/bin/env ruby

require 'sinatra'
require 'json'
require 'yaml'
require 'net/http'
require 'uri'

consul_host=ARGV[0]
set :environment, :production

get '/:tag' do
  tag=params[:tag]
  output=params[:output]
  "Checking consul for all services tagged with #{tag}"

  services_with_tag=Array.new
  #Get all consul services
  services=JSON.parse(Net::HTTP.get_response(URI.parse("http://#{consul_host}/v1/catalog/services")).body)
  services.each do |service|
    if service[1].include?(tag)
      services_with_tag.push(service[0])
    end
  end

  master_list=Array.new
  services_with_tag.each do |service|
    service_uri=URI.parse("http://#{consul_host}")
    service_info=JSON.parse(Net::HTTP.get_response(URI.parse("http://#{consul_host}/v1/catalog/service/#{service}?tag=#{tag}")).body)
    nodes=Array.new
    ips=Array.new
    port=service_info[0]["ServicePort"]
    service_info.each do |i|
      ips.push(i["Address"])
      nodes.push(i["Node"])
    end
    service_obj={:name=>service, :port=>port, :nodes=>nodes, :ips=>ips}
    master_list.push(service_obj)
  end

  if output == 'json'
    master_list.to_json
  elsif output == 'yaml'
    master_list.to_yaml
  elsif output == nil or output == ""
    erb :index, :locals => {:master_list => master_list}
  end
end
